language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install --upgrade pip setuptools wheel
  - pip install pytest codecov
  - pip install --only-binary=numpy numpy affine shapely dateutil
  - pip install -e .[test]
script:
  - coverage run --source=dg_calibration -m pytest -v
after_success:
  - codecov
